export const MOCK_TRENDING = [
  {
    id: 1,
    slug: 'understanding-rizz',
    title: 'Understanding "Rizz" – The Latest Gen Z Dating Slang',
    excerpt: 'Learn what "rizz" means and how young people are using it in their daily conversations and on social media.',
    category: 'Slang',
    platform: 'TikTok',
    tags: ['TikTok', 'Slang'],
    readTime: 4,
    publishedAt: '2026-03-04',
    imageUrl: null,
  },
  {
    id: 2,
    slug: 'get-ready-with-me-trend',
    title: 'The "Get Ready With Me" Trend: What Parents Need to Know',
    excerpt: 'GRWM videos are everywhere. Understand this popular content format and its impact on young viewers.',
    category: 'Trends',
    platform: 'TikTok',
    tags: ['TikTok', 'Trends'],
    readTime: 5,
    publishedAt: '2026-03-03',
    imageUrl: null,
  },
  {
    id: 3,
    slug: 'bereal-app-explained',
    title: 'BeReal App Explained: The "Anti-Instagram" Social Network',
    excerpt: 'BeReal encourages authenticity by giving users just 2 minutes to post an unfiltered photo each day.',
    category: 'Apps',
    platform: 'BeReal',
    tags: ['BeReal', 'Apps'],
    readTime: 6,
    publishedAt: '2026-03-02',
    imageUrl: null,
  },
]

export const MOCK_ARTICLES = [
  ...MOCK_TRENDING,
  {
    id: 4,
    slug: 'discord-for-parents',
    title: 'Discord: What Parents Need to Know About This Gaming Chat App',
    excerpt: 'Discord started as a gaming platform but is now used by teens for nearly everything. Here is what you should know.',
    category: 'Apps',
    platform: 'Discord',
    tags: ['Discord', 'Apps', 'Safety'],
    readTime: 7,
    publishedAt: '2026-03-01',
    imageUrl: null,
  },
  {
    id: 5,
    slug: 'instagram-reels-explained',
    title: 'Instagram Reels Explained: Short-Form Video for Teens',
    excerpt: 'Reels have become the dominant way teens consume and create content on Instagram. We break it down.',
    category: 'Features',
    platform: 'Instagram',
    tags: ['Instagram', 'Features'],
    readTime: 5,
    publishedAt: '2026-02-28',
    imageUrl: null,
  },
  {
    id: 6,
    slug: 'online-safety-tips',
    title: '10 Online Safety Tips Every Parent Should Teach Their Teen',
    excerpt: 'From strong passwords to recognizing grooming behavior — practical advice to keep your teen safe online.',
    category: 'Safety',
    platform: null,
    tags: ['Safety'],
    readTime: 8,
    publishedAt: '2026-02-27',
    imageUrl: null,
  },
]

export const CATEGORIES = ['All', 'Slang', 'Trends', 'Apps', 'Features', 'Safety']
export const PLATFORMS  = ['All', 'TikTok', 'Instagram', 'YouTube', 'Discord', 'BeReal']
